spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: never
      data-locations: classpath:data.sql

  mail:
    default-encoding: UTF-8
    host: smtp.mail.ru
    username:
    password:
    port: 465
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true



logging:
  level:
    ru:
      info
    org:
      hibernate:
        SQL:
          DEBUG
      type:
        trace






