-- drop table ORGANIZATION_WORKER;
--
-- drop table ORGANIZATION;
--
-- alter table WORKER
-- drop constraint WORKER_WORK_HISTORY;
--
-- drop table WORK_HISTORY;
--
-- drop table DAYS_OF;
--
-- drop table EMPLOY_POS;
--
-- drop table SICK_DAYS;
--
-- drop table VACATION;
--
-- drop table WORKER;






create table if not EXISTS organization
(
    org_id BIGINT GENERATED BY DEFAULT  AS IDENTITY NOT NULL,
    name VARCHAR not null,
    inn VARCHAR not null,
    ogrn VARCHAR not null,
    address VARCHAR not null,
    phone_number VARCHAR not null,
    zip VARCHAR not null,
    CONSTRAINT pk_organization PRIMARY KEY (org_id)

);
create table if not EXISTS worker
(
    worker_id    BIGINT GENERATED BY DEFAULT  AS IDENTITY NOT NULL,
    work_now     BOOLEAN not null,
    name         VARCHAR not null,
    surname      VARCHAR not null,
    patronymic   VARCHAR not null,
    birthday     DATE not null,
    phone_number VARCHAR not null,
    org_id BIGINT  REFERENCES organization (org_id),
--     history_id BIGINT,
    CONSTRAINT pk_worker PRIMARY KEY (worker_id)
    );

CREATE TABLE IF NOT EXISTS organization_worker (
    worker_id BIGINT  REFERENCES worker (worker_id),
    org_id BIGINT  REFERENCES organization (org_id),
    CONSTRAINT pk_organization_worker PRIMARY KEY (worker_id, org_id)
    );

create table if not EXISTS employ_pos
(
    empl_id BIGINT GENERATED BY DEFAULT  AS IDENTITY NOT NULL,
    position VARCHAR not null,
    job_description VARCHAR not null,
    CONSTRAINT pk_empl PRIMARY KEY (empl_id)
    );



create table if not EXISTS work_history
(
    work_history_id BIGINT GENERATED BY DEFAULT  AS IDENTITY NOT NULL,
    work_now BOOLEAN,
    empl_id BIGINT REFERENCES employ_pos (empl_id),
    start_work DATE not null,
    end_work DATE,
    worker_id BIGINT,
--     nwd BIGINT,
    CONSTRAINT pk_work_history PRIMARY KEY (work_history_id)
    );

CREATE TABLE IF NOT EXISTS not_work_days
(
    nwd_id BIGINT  GENERATED BY DEFAULT  AS IDENTITY NOT NULL,
    start_date DATE not null,
    end_date DATE,
    note VARCHAR,
    work_history_id BIGINT,
    type_day VARCHAR,
    CONSTRAINT pk_vacation PRIMARY KEY (nwd_id)
    );

-- ALTER TABLE worker
--     ADD CONSTRAINT WORKER_WORK_HISTORY FOREIGN KEY (history_id) REFERENCES work_history (work_history_id);

CREATE TABLE IF NOT EXISTS work_history_notWD (
    work_history_id BIGINT  REFERENCES work_history (work_history_id),
    nwd_id BIGINT  REFERENCES not_work_days (nwd_id),
    CONSTRAINT pk_work_history_notWD PRIMARY KEY (work_history_id, nwd_id)
    );

CREATE TABLE IF NOT EXISTS WORKER_WORK_HISTORY (
    worker_id BIGINT  REFERENCES worker (worker_id),
    work_history_id BIGINT  REFERENCES work_history (work_history_id),
    CONSTRAINT pk_worker_history_work PRIMARY KEY (worker_id, work_history_id)
    );



