
create table if not EXISTS worker
(
    worker_id    BIGINT GENERATED BY DEFAULT  AS IDENTITY NOT NULL,
    work_now     BOOLEAN not null,
    name         VARCHAR not null,
    surname      VARCHAR not null,
    patronymic   VARCHAR not null,
    birthday     DATE,
    phone_number VARCHAR not null,
--     work_history_id BIGINT REFERENCES WORKER_WORK_HISTORY (worker_id),
    work_history_id BIGINT not null,
    CONSTRAINT pk_worker PRIMARY KEY (worker_id)
);

create table if not EXISTS organization
(
    org_id BIGINT GENERATED BY DEFAULT  AS IDENTITY NOT NULL,
    name VARCHAR,
    inn VARCHAR,
    ogrn VARCHAR,
    address VARCHAR,
    phone_number VARCHAR,
    zip VARCHAR,
    workers BIGINT REFERENCES worker (worker_id),
    CONSTRAINT pk_organization PRIMARY KEY (org_id)

);

CREATE TABLE IF NOT EXISTS organization_worker (
    worker_id BIGINT  REFERENCES worker (worker_id),
    org_id BIGINT  REFERENCES organization (org_id),
    CONSTRAINT pk_organization_worker PRIMARY KEY (worker_id, org_id)
    );

create table if not EXISTS employ_pos
(
    empl_id BIGINT GENERATED BY DEFAULT  AS IDENTITY NOT NULL,
    position VARCHAR not null,
    job_description VARCHAR not null,
    CONSTRAINT pk_empl PRIMARY KEY (empl_id)
    );

CREATE TABLE IF NOT EXISTS vacation
(
    id BIGINT  GENERATED BY DEFAULT  AS IDENTITY NOT NULL,
    start_date DATE not null,
    end_date DATE,
    note VARCHAR,
    CONSTRAINT pk_vacation PRIMARY KEY (id)
    );
CREATE TABLE IF NOT EXISTS sick_days
(
    id BIGINT  GENERATED BY DEFAULT  AS IDENTITY NOT NULL,
    start_date DATE not null,
    end_date DATE,
    note VARCHAR,
    CONSTRAINT pk_sick_days PRIMARY KEY (id)
    );
CREATE TABLE IF NOT EXISTS days_of
(
    id BIGINT  GENERATED BY DEFAULT  AS IDENTITY NOT NULL,
    start_date DATE not null,
    end_date DATE,
    note VARCHAR,
    CONSTRAINT pk_days_of PRIMARY KEY (id)
    );

create table if not EXISTS work_history
(
    work_history_id BIGINT GENERATED BY DEFAULT  AS IDENTITY NOT NULL,
    work_now BOOLEAN,
    empl_id BIGINT REFERENCES employ_pos (empl_id),
    start_work DATE not null,
    end_work DATE,
    days_of_id BIGINT REFERENCES days_of (id),
    sick_days_id BIGINT REFERENCES sick_days (id),
    vacation BIGINT REFERENCES vacation (id),
    worker_id BIGINT REFERENCES worker (worker_id),

    CONSTRAINT pk_work_history PRIMARY KEY (work_history_id)
);

-- CREATE TABLE IF NOT EXISTS WORKER_WORK_HISTORY (
--     worker_id BIGINT  REFERENCES worker (worker_id),
--     work_history_id BIGINT  REFERENCES work_history (work_history_id),
--     CONSTRAINT pk_worker_history_work PRIMARY KEY (worker_id, work_history_id)
--     );


-- ALTER TABLE worker
--     ADD CONSTRAINT WORKER_WORK_HISTORY FOREIGN KEY (work_history_id) REFERENCES work_history (work_history_id);



